# Copyright 2026 Fractalyze Inc. All rights reserved.

name: PR Review Notification

on:
  pull_request:
    types: [review_requested]

jobs:
  notify-review-request:
    if: >-
      github.event_name == 'pull_request'
      && github.event.pull_request.draft == false
    uses: fractalyze/pr-review-bot/.github/workflows/handle-review-request.yml@main
    with:
      pr_url: ${{ github.event.pull_request.html_url }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_number: ${{ github.event.number }}
      repo_name: ${{ github.repository }}
      reviewer_login: ${{ github.event.requested_reviewer.login }}
      requested_by_login: ${{ github.event.sender.login }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      PR_REVIEW_SLACK_BOT_TOKEN: ${{ secrets.PR_REVIEW_SLACK_BOT_TOKEN }}
